version: '3.1'
networks:
  nextcloud:
volumes:
  nextcloud:
  db:
  libreoffice:
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud@123
      POSTGRES_DB: nextcloud
      PGDATA: /data/postgres
    volumes:
       - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - nextcloud
    restart: unless-stopped

  nextcloud:
    image: nextcloud:20.0-fpm
    #restart: always
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      #- ./custom_apps:/var/www/html/custom_apps:rw
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud@123
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin@123
      - NEXTCLOUD_TRUSTED_DOMAINS='10.0.152.230'
    depends_on:
      - db
    networks:
      - nextcloud

  webapp:
    build: .
    image: webapp:latest
    hostname: webapp
    #restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - nextcloud
    networks:
      nextcloud:
        aliases:
            - webapp.local